import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//add ethers
import { BigNumber, ethers } from "ethers";
import { useAccount, useClient } from "wagmi";
import { useEffect, useState } from "react";
import { Main } from 'next/document';
export default function Home() {
  // use state to store the value of the input
  const [input, setInput] = useState("");
  const { isConnected } = useAccount();
  //create a provider
  const provider = ethers.getDefaultProvider("goerli");
  //create address random
  var random;
  var randomAddress;
  var randomPrivateKey;
  var randomMnemonic;
  var randomSigner;
  var ethBalance = 0;

  function getBalance() {
    console.log("getBalance");
    console.log(ethBalance);
  }
  async function createwallet() {
    console.log("createwallet");
    const random = await ethers.Wallet.createRandom();
    console.log(random);
    setInput(random.address);
    const randomAddress = random.address;
    const randomPrivateKey = random.privateKey;
    const randomMnemonic = random.mnemonic;
    const randomSigner = await random.connect(provider);
    const ethBalance = await randomSigner.getBalance();
    console.log(ethBalance);
  }
  function requestTokens() {
    //todo: request tokens to be minted in the backend
    console.log("requestTokens");
    //after the transaction you can call getBalance

  }
  function connectBallot() {
    //TODO: connect to the ballot contract
    console.log("connectBallot");

  }
  return (
    
    <div className="container-fluid">
    <Head>
        <title>Ballot token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    <section className="jumbotron text-center">
      <div className="container">
        <h1 className="jumbotron-heading">Ballot token</h1>
        <p className="lead text-muted">Something short.</p>
        <p>
          <a href="#" className="btn btn-primary my-2">Main call to action</a>
          <a href="#" className="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </section>

    <div className="album py-5 bg-light">
        <div className="row">
        
          <div className="col-sm">
            <h2>Ballot token</h2>
            <p>Connect to the ballot contract</p>
            <button className='btn btn-primary' onClick={connectBallot}>Connect</button>
          </div>
          <div className="col-sm">
            <h2>Request tokens</h2>
            <p>Request tokens to be minted in the backend</p>
            <button className='btn btn-primary'  onClick={requestTokens}>Request</button>
          </div>
          <div className="col-sm">
            <h2>Get balance</h2>
            <p>Get the balance of the connected account</p>
            <button className='btn btn-primary' onClick={getBalance}>Get balance</button>
          </div>
          <div className="col-sm">
            <h2>Create wallet</h2>
            <p>Create a random wallet</p>
            <button className='btn btn-primary' onClick={createwallet}>Create wallet</button>
            <p>Address: {input}</p>
          </div>
        </div>
        </div>
      </div>
  )

}
